name = "email-worker-github"
main = "src/index.ts"
compatibility_date = "2023-02-12"
usage_model = "unbound"

analytics_engine_datasets = [
	{ binding = "STATS", dataset = "GITHUB_EMAIL_STATS" }
]


# Worker defines a binding, named "QUEUE", which gives it a capability
# to send messages to a Queue, named "my-queue".
[[queues.producers]]
  queue = "email-worker-github"
  binding = "QUEUE"

# Worker also receives messages from the Queue, named "my-queue".
[[queues.consumers]]
  queue = "email-worker-github"
  max_batch_size = 100   # Max messages per batch
  max_batch_timeout = 30 # Max seconds to wait before batch is full
  max_retries = 3       # Max retries per batch